services:

  app:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    env_file:
      - ./.env
    volumes:
      - ./files:/usr/src/redmine/files


  db:
    container_name: redmine-db
    build:
      context: .
      dockerfile: ./postgres-image/Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: untilov/redmine-db
    restart: always
    hostname: redmine
    expose:
      - 5432
    ports:
      - 5632:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-backup:/backup
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - ./.env

networks:
  default:
    name: redmine-network
    driver: bridge
    # external: true
