#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE redmine WITH
		LOGIN
		NOSUPERUSER
		INHERIT
		NOCREATEDB
		NOCREATEROLE
		NOREPLICATION
		PASSWORD 'TopSecret123';
	CREATE DATABASE redmine
		WITH
		OWNER = redmine
		ENCODING = 'UTF8'
		LC_COLLATE = 'en_US.utf8'
		LC_CTYPE = 'en_US.utf8'
		LOCALE_PROVIDER = 'libc'
		TABLESPACE = pg_default
		CONNECTION LIMIT = -1
		IS_TEMPLATE = False;
	GRANT TEMPORARY, CONNECT ON DATABASE redmine TO PUBLIC;
	GRANT ALL PRIVILEGES ON DATABASE redmine TO redmine;
EOSQL
